### ISSUE TITLE
Get a list of lists

### ISSUE THREAD

**Issue by HarryBosh** [nztim/mailchimp#1]
Hello!

Maybe this is a feature request? I am unable to use the wrapper following instructions from the source.
https://github.com/drewm/mailchimp-api/tree/api-v3

Examples
Start by use-ing the class and creating an instance with your API key
use \DrewM\MailChimp\MailChimp;
$MailChimp = new MailChimp('abc123abc123abc123abc123abc123-us1')
Then, list all the mailing lists (with a get on the lists method)
$result = $MailChimp->get('lists');
print_r($result);

-------------------------------------
In laravel
$MailChimp = new MailChimp(env('MC_KEY'));
$result = $MailChimp->get('lists');
dd($result);

Call to undefined method NZTim\Mailchimp\MailchimpFacade::get()

What am i missing?

**Comment by nztim** [comment]
Hi!

The information you posted appears to mostly relate to Drew McLellan's package. And in terms of the error it appears that you have imported the NZTim\Mailchimp\MailchimpFacade class and are calling `get()`, which doesn't exist (it's a method on Drew's package).

If you would like to use this package, I recommend double-checking the installation instructions  (compose require, service provider, facade reference). Then `use Mailchimp;`, and use the methods from the instructions (https://github.com/nztim/mailchimp), e.g.:
```
Mailchimp::subscribe($listId, $emailAddress, $mergeFields = [], $confirm = false)
```

Hope that helps :)

**Comment by nztim** [comment]
If you want to use Drew's then I would make sure you have installed that package, then double-check the use statement, then it should work as per his instructions.
