### ISSUE TITLE
Larave 5.5 Support

### ISSUE THREAD

**Issue by masiur** [nztim/mailchimp#13]
I had to have it worked on laravel 5.5, since there is no support. 
config publish did not work. 
The package was not auto-discovered. 
But everything else was fine.

**Comment by nztim** [comment]
Hi, I've added auto-discovery and tagged a new version. 
I think that will solve the config publishing issue, but please give it a try and let me know how it goes.

**Comment by masiur** [comment]
Now, it's playing cool. Thank you so much.
