### ISSUE TITLE
subscribe()

### ISSUE THREAD

**Issue by nikosv** [nztim/mailchimp#2]
In the code comments you wrote
``
// Add/update the subscriber - PUT does both
``
It seems that this is not true. It only adds.

**Comment by nztim** [comment]
For the Mailchimp API call used in the method it adds and updates, see the documentation:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/

Are you having problems using it?

**Comment by nikosv** [comment]
In all my tests it created the subscriber but no luck updating any fields (other than email) related to that subscriber

**Comment by nztim** [comment]
Same for me, I'll take a look at it. Thanks for bringing it up!

**Comment by nztim** [comment]
I rewrote the package and the bug should be resolved now. 
Note that upgrading means you need to catch exceptions now, see the readme.

If you use it please let me know how you get on.

**Comment by nikosv** [comment]
Yeap works great now
