### ISSUE TITLE
Mailchimp resppnses

### ISSUE THREAD

**Issue by calder12** [nztim/mailchimp#21]
This isn't really an issue, more a feature request. It would be really nice if the subscribe function returned the actual Mailchimp response. Right now it appears to return nothing and as such you have to assume it succeeded. Or am I missing something?

**Comment by nztim** [comment]
I don't think subscribe() can fail without throwing an exception. Does that solve the problem for you, or do you have other reasons for wanting the response information?

**Comment by calder12** [comment]
Perhaps I am mistaken, I tried to look it up but honestly Mailchimp's docs even for the basic site use are getting bad.

I thought it returned a status, like already subscribed or an error, no?

**Comment by nztim** [comment]
The API info is here:
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash

This method is made so you don't have to worry whether they are already subscribed or not, if they are already a subscriber they won't be asked to reconfirm. 

Was there something else you needed to know? If you want to access the API directly and get everything back you can always use `Mailchimp::api($method, $endpoint, $data = []);`.

**Comment by calder12** [comment]
Thanks, and I very much appreciate your work on this. I am sending the request via AJAX so if there was a response like already subscribed I wanted to display that. I'll dig into your suggestion. Sorry for wasting your time!

**Comment by nztim** [comment]
If you need to handle the already-subscribed situation differently then your handler could call check() first and immediately respond if true. 

You're welcome and I hope the code is useful.

**Comment by calder12** [comment]
Your code saved me hitting the API directly, so very useful. Thank you again for your help!
