### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by CarlosEduardoXtesting** [nztim/mailchimp#24]
Non-static method NZTim\Mailchimp\Mailchimp::subscribe() should not be called statically

**Comment by CarlosEduardoXtesting** [comment]
What does this error mean?

**Comment by nztim** [comment]
It's complaining because `subscribe()` is being called on the Mailchimp class directly rather than using the facade. Your imports probably have `use NZTim\Mailchimp\Mailchimp;`, change that to `use Mailchimp;` and it will likely work.

**Comment by CarlosEduardoXtesting** [comment]
it helped a lot. Thank You.
