### ISSUE TITLE
Error when using api() method

### ISSUE THREAD

**Issue by nikosv** [nztim/mailchimp#3]
When using the api method to delete a user like so
``
\Mailchimp::api('delete', '/lists/{list_id}/members/'.md5(strtolower({email})));
``
i get 

``
FatalThrowableError in MailchimpApi.php line 71:
Type error: Return value of NZTim\Mailchimp\MailchimpApi::call() must be of the type array, null returned
``

Subscriber is successfully deleted though

**Comment by nztim** [comment]
Thanks for the report. It wasn't handling API calls with empty responses, v3.1.2 should resolve this.
