### ISSUE TITLE
Compose cannot find the simplehttp

### ISSUE THREAD

**Issue by AKMANSoft** [nztim/mailchimp#30]
Problem 1
    - Root composer.json requires nztim/simplehttp, it could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Root composer.json requires nztim/mailchimp ^4.1 -> satisfiable by nztim/mailchimp[v4.1].
    - nztim/mailchimp v4.1 requires nztim/simplehttp ^2.0 -> could not be found in any version, there may be a typo in the package name.

**Comment by nztim** [comment]
Thanks for reporting this, please try v4.2.
