### ISSUE TITLE
Tag to member

### ISSUE THREAD

**Issue by eduardojesustun** [nztim/mailchimp#33]
How to add TAGS to member?

Mailchimp::subscribe(
                $list->ch_audience_id,
                $request->email,
                [
                    'tags' => ['test']
                ],
                false
);

This example not working, add to member to my list but no tags

**Comment by nztim** [comment]
The third argument on the subscribe method handles merge fields, to work with member tags you will need to use the endpoint directly. The API reference is [here](https://mailchimp.com/developer/marketing/api/list-member-tags/add-or-remove-member-tags/), I haven't tried it but I expect it would look like this:

```
Mailchimp::api("post", "/lists/{$listId}/members/{$subscriberHash}/tags", ["tags" => [["name" => "thetag", "status" => "active"]]);
```

Note the requirements for a tag in the docs, each one must have a name and a status.
