### ISSUE TITLE
Remove tags

### ISSUE THREAD

**Issue by upperhouse** [nztim/mailchimp#37]
Hi there.
Is there a way to remove tags? I tried the addTags method and just passing an empty value/array, but no change. The previously added tag remained.
Thanks for your time.

**Comment by nztim** [comment]
I've added getTags(), removeTags() and removeAllTags() now, please give it a try and let me know if you have any problems.

**Comment by upperhouse** [comment]
This is working great. Thank you so much for setting this up so quickly!

**Comment by nztim** [comment]
Sure no worries, hope it works well for you.
