### ISSUE TITLE
Create Unsubscribe Method

### ISSUE THREAD

**Issue by andreladocruz** [nztim/mailchimp#8]
I wrote the following method in my code:

public function unsubscribe($listId, $email)
  {
    if ($this->mc->check($listId, $email))
    {
      return $this->mc->api('delete', '/lists/'.$listId.'/members/'.md5($email).'/');
    }
  }

And it worked. ;) 

Bless,

**Comment by nztim** [comment]
Cool! Good luck with your mailing list :)
